class Soldier is LandUnit -> {  
    constructor(number id) -> { 
        number self.id = id; 
    }; 
    function number Pe(Cell a, Cell b)->{
        number e = a.row;
        number i = b.col;
        return self.id; 
    };
}; 
& 

List b = [[1]];
function number W(number a) -> {
    b.append(1); 
    while a lte 5 -> {
        a = a + 1;
    }; 
    return a;
}; 

number a = 2;
if a lt 2 ->{
    a=3;
}
else ->{
    a=1;
};


BSUnit s=Soldier(1.4);

print(a);
