class Soldier is LandUnit -> {  
    constructor(number id) -> { 
        number self.id = id; 
    }; 
}; 
class Archer is LandUnit -> {  
    constructor(number id, number life_points) -> { 
        number self.id = id; 
        number self.life_points = life_points; 
    }; 
}; 
& 

if 3 lt 2->
{
    number i = 4;
};

function number Q(bool a, number c)->{
    return c;
};

bool a = True;
number d = Q(a,4);

Soldier s=Soldier(d);

print(Q(a,3.2));