class Soldier is LandUnit -> {  
    constructor(number id) -> { 
        number self.id = id + 3 * 5^-2; 
    }; 
};
class Archer is LandUnit -> {  
    constructor(number id, number life_points) -> { 
        number self.id = id; 
        number self.life_points = life_points; 
    }; 
}; 
&

function number W(number a) -> { 
    if a lt 0 and a eq 0 -> { 
        return -1 * a;  
    } 
    elif a gt 1 -> {
        return 4;
    } 
    else -> { 
        return a; 
    }; 
};

Soldier b = Soldier(1); 
Soldier bOne = Soldier(3); 
BSUnit a = Archer(1, 10);
 
a = b;