class Soldier is LandUnit -> {  
    constructor(number id) -> { 
        number this.id = id + 3 * 5^-2; 
    }; 
    function number W(number a) -> { 
        if a lt 0 and a eq 0 -> { 
            return -1 * a;  
        } 
        elif a gt 1 -> {
            return 4;
        } 
        else -> { 
            return a; 
        }; 
    };
};
class Archer is LandUnit -> {  
    constructor(number id, number life_points) -> { 
        number this.id = id; 
        number this.life_points = life_points; 
    }; 
}; 
& 
Soldier b = Soldier(1); 
Soldier bOne = Soldier(3); 
Archer a = Archer(1, 10); 
if a eq None -> { 
    a = a + 1; 
}; 
a = [1,2,3, [1,2,3,4] ];